version: '3.8'

services:
  treatsdreams:
    build: 
      context: https://github.com/Mikerstrong/treatsndreams.git
      dockerfile: Dockerfile
    ports:
      - "8547:8547"
    volumes:
      - treatsdreams_data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8547
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - DATA_DIR=/app/data
    restart: unless-stopped
    container_name: treatsdreams-app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8547/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=treatsdreams"
      - "app=treatsdreams"
      - "version=1.0"

volumes:
  treatsdreams_data:
    driver: local
    labels:
      - "app=treatsdreams"
